name: Scan for leaks, build and scan image, and push.

on:
  push:
    branches: [main, release]

env:
  REGISTRY: docker.io
  IMAGE_NAME: dummyapi
  IMAGE_REPO: docker.io/${{ secrets.DOCKER_USERNAME }}/dummyapi
  DOCKERFILE_PATH: ./Dockerfile
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-scan-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_NOTIFY_USER_LIST: "@swiss-superman,@KaoKsn"

      - name: Setup docker buildx.
        uses: docker/setup-buildx-action@v3

      - name: Build the container image locally
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_REPO }}:latest

      - name: Checking if the image is present locally.
        run:
          docker image inspect "${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}"

      - name: Trivy image scan for critical vulnerabilites in os, libarires.
        uses: aquasecurity/trivy-action@v0.36.0
        with: 
          image-ref: ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          format: "json"
          vuln-type: "os,library"
          severity: "CRITICAL"
          exit-code: "1"
          scanners: "vuln"

      - name: container registry login and auth
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: publish the image on docker.io
        run: |
          docker push "${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG}}"
          docker push "${{ env.IMAGE_REPO }}:latest"
