name: Greet a first time contributor

on:
  issues:
    type: [opened]
  pull_request:
    type: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: greet the first time contributor.
        uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Welcome to the CICD project. This seems to be your first issue here.
            Please read the CODE_OF_CONDUCT.md to understand our community interaction standards
            Read CONTRIBUTING.md to learn the rules for contributing to this project.
            We assume that you have already read these documents atleast once before creating this request.

            Thanks and Regards.
            Project CICD team.
          pr-message: |
            Welcome to the CICD project. This looks like your first pull request here.
            Please read the CODE_OF_CONDUCT.md to understand our community interaction standards
            Read CONTRIBUTING.md to learn the rules for contributing to this project.
            We assume that you have already read these documents atleast once before creating this request.

            Thanks and Regards.
            Project CICD team.
