name: Scanner and Normalization.

on:
  workflow_dispatch:
  push:
    branches: [main, release]

env:
  REGISTRY: docker.io
  IMAGE_TAG: ${{ github.sha }}
  DOCKERFILE_PATH: ./Dockerfile
  IMAGE_NAME: dummyapi

jobs:
  gitleaks-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0

      - name: Scan for secrets with Gitleaks
        run: |
          mkdir -p /tmp/scan-reports
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -v /tmp/scan-reports:/output \
            zricethezav/gitleaks:latest detect \
            --source /repo \
            --report-format json \
            --report-path /output/gitleaks-report.json \
            --exit-code 0
        continue-on-error: true
      - name: Normalize gitleaks output
        run: |
          if [ -f /tmp/scan-reports/gitleaks-report.json ]; then
            jq '[
              .[] |
              {
                File: .File,
                StartLine: .StartLine,
                EndLine: .EndLine,
                Commit: .Commit
              }
            ]' \
            /tmp/scan-reports/gitleaks-report.json \
            > /tmp/gitleaks-report-norm.json
          else
            echo '[]' > /tmp/gitleaks-report-norm.json
          fi
      - name: Upload Gitleaks report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        if: always()
        with:
          name: gitleaks-report
          path: /tmp/gitleaks-report-norm.json
          retention-days: 30

  semgrep-scan:
    runs-on: ubuntu-24.04
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0

      - name: SAST using semgrep
        run: semgrep --config auto --json --severity WARNING --exclude '*/.github/workflows/*.yml' . > /tmp/semgrep-report.json
      - name: Normalize semgrep output
        run: |
          cat /tmp/semgrep-report.json | jq '[
              .results[] |
              {
                  path: .path,
                  start: .start,
                  end: .end,
                  message: (.extra.message // null),
                  severity: (.extra.severity // null),
                  validation_state: (.extra.validation_state // null),

                  cwe: (.extra.metadata.cwe // null),
                  likelihood: (.extra.metadata.likelihood // null),
                  impact: (.extra.metadata.impact // null),
                  references: (.extra.metadata.references // null),
                  shortlink: (.extra.metadata.shortlink // null)
              }]
              ' > /tmp/semgrep-report-norm.json
      - name: Upload Semgrep report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        if: always()
        with:
          name: semgrep-report
          path: /tmp/semgrep-report-norm.json
          retention-days: 30

  checkov-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 #v7.0.0
        with:
          python-version: "3.11"
      - name: Install Checkov
        run: pip install checkov
      - name: Scan the repo for infrastructure files
        run: |
          checkov -f target.tf \
                  --framework all \
                  --output json \
                  --output-file-path /tmp/checkov-report.json, \
                  --quiet \
                  --soft-fail
        continue-on-error: true
      - name: Normalize checkov output
        if: always()
        run: |
          if [ -f /tmp/checkov-report.json ]; then
            jq '[
              .results.failed_checks[]? |
              {
                check_id: .check_id,
                check_name: .check_name,
                severity: (.severity // null),
                short_description: (.short_description // null),
                resource_address: (.resource_address // null),
                file_abs_path: (.file_abs_path // null),
                file_line_range: (.file_line_range // null),
                code_block: (
                  [.code_block[]? | .[1]]
                  | join("\n")
                ),
                guideline: (.guideline // null),
                fixed_definition: (.fixed_definition // null)
              }
            ]' \
            /tmp/checkov-report.json \
            > /tmp/checkov-report-norm.json
            echo "Report was normalized"
          else
            echo '[]' > /tmp/checkov-report-norm.json
          fi
      - name: Upload checkov report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: checkov-report
          path: /tmp/checkov-report-norm.json
          retention-days: 30

  trivy-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0

      - name: Setup docker buildx.
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e #v4.3.0

      - name: Build the container image locally
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a #v7.3.0
        env:
          IMAGE_REPO: docker.io/${{ secrets.DOCKER_USERNAME }}/dummyapi
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_REPO }}:latest

      - name: Trivy image scan for critical and high vulnerabilites in os, libarires.
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 #v0.36.0
        env:
          IMAGE_REPO: docker.io/${{ secrets.DOCKER_USERNAME }}/dummyapi
        with:
          image-ref: ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          format: "json"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          output: /tmp/trivy-report.json
          exit-code: "0" # Change to 1 when needed.
          scanners: "vuln"
        continue-on-error: true
      - name: Normalize the json output from trivy
        if: always()
        run: |
          jq '[
            .Results[]? |
            {
              Target: .Target,
              Vulnerabilities: [
                .Vulnerabilities[]? |
                {
                  VulnerabilityID: .VulnerabilityID,
                  Title: .Title,
                  Severity: .Severity,
                  CVSS: .CVSS,
                  Status: .Status,
                  InstalledVersion: .InstalledVersion,
                  FixedVersion: .FixedVersion,
                  PkgName: .PkgName,
                  PkgIdentifier: .PkgIdentifier,
                  DataSource: .DataSource,
                  References: .References
                }
              ]
            }
          ]' /tmp/trivy-report.json > /tmp/trivy-report-norm.json
      - name: Upload trivy report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: trivy-report
          path: /tmp/trivy-report-norm.json
          retention-days: 30

  consolidate-reports:
    needs: [gitleaks-scan, trivy-scan, semgrep-scan, checkov-scan]
    runs-on: ubuntu-22.04
    steps:
      - name: Download normalized reports from all the tools
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          path: /tmp/results
      - name: Consolidate the report outputs
        shell: bash
        # actions/download-artifact downloads each under its name i.e
        # gitleaks-report/gitleaks-report-norm.json
        run: |
          report_path="/tmp/results"
          consolidated_report="/tmp/consolidated-report.json"

          find "$report_path" -name "*-report-norm.json" | while read -r f; do
              jq -n \
                --arg toolname "$(basename "$f" -norm.json)" \
                --arg file "$f" \
                --slurpfile content "$f" '
                    ($toolname | if contains("checkov") then  {tool: "checkov", categories: ["misconfiguration"]}
                    elif contains("gitleaks") then {tool: "gitleaks", categories: ["secrets"]}
                    elif contains("semgrep") then {tool: "semgrep", categories: ["sast"]}
                    elif contains("trivy") then {tool: "trivy", categories: ["vulnerabilities", "containers"]}
                    else {tool: $toolname, categories: ["general"]} end) as $meta |
                {
                    categories: $meta.categories,
                    tool: $meta.tool,
                    resultsource: $file,
                    results: $content[0]
                }
                '
          done | jq -s '.' >| "$consolidated_report"
      - name: Upload the consolidated report.
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: consolidated-report.json
          path: /tmp/consolidated-report.json
          retention-days: 45
